logging:
  level:
    root: INFO
    com:
      fedex: DEBUG
      
spring:
  datasource:
    url: jdbc:sqlserver://fod-sql-dev.8ac16ee20438.database.windows.net:1433;database=fod-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.8ac16ee20438.database.windows.net;loginTimeout=30;
    username: ${AZ_SQL_USERNAME}
    password: ${AZ_SQL_PASSWORD}
  jms: 
    servicebus:
      connection-string: ${ACTIVITY_QUEUE_CONNECTION}
      idle-timeout: 1800000
      pricing-tier: standard
    
    
google:
  api:
    url: https://maps.googleapis.com/maps/api/geocode/json?address=
    key: ${GOOGLE_API_KEY}
    
vehicle: 
  service:
    endpoint: https://fedexondemanddev.azure-api.net/v2/sim/vehicle
    
roxo:
  ssl:
    password: ${ROXO_PASSWORD}   
    
opl:
  api:
    url: https://fedexondemanddev.azure-api.net/v2/eta
