logging:
  level:
    root: INFO
    com:
      fedex: DEBUG

spring:
  application:
    name: account-service
  flyway:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  mvc: 
    throw-exception-if-no-handler-found: true
  web: 
    resources: 
      add-mappings: false
#   profiles:
#     active: local
  datasource:
    url: jdbc:sqlserver://fod-sql-dev.public.8ac16ee20438.database.windows.net:3342;database=fod-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.8ac16ee20438.database.windows.net;loginTimeout=30;
    username: ${AZ_SQL_USERNAME}
    password: ${AZ_SQL_PASSWORD}
  jms: 
    servicebus:
      connection-string: ${ACTIVITY_QUEUE_CONNECTION}
      idle-timeout: 1800000
      pricing-tier: standard
    
management:
  endpoints:
    web:
      exposure:
        include: info, health, refresh, configprops
        
info:
  app:
    name: account-service
    description: FedEx-OnDemand - Account Service
    
# this needs to be in the common application properties
swagger: 
  service: 
    contact: 
      email: CAVS@fedex.com
      name: "FedEx OnDemand Development Team"
      url: "https://fedex.com/"
    description: "This service is used for handling logic with the FedEx-OnDemand Account Service. Anything that need to be done on the Site/Customer resources is supported in this API REST Serive."
    license: 
      url: "https://fedex.com/licence"
    name: "FOD Account Service API"
    tos: 
      url: "https://cavs.fexdex.com/termsofuse"
    version: v1
    group: CAVS Open Api Group
    
google:
  api:
    url: https://maps.googleapis.com/maps/api/geocode/json?address=
    key: ${GOOGLE_API_KEY}
    
vehicle: 
  service:
    endpoint: https://fedexondemanddev.azure-api.net/v2/sim/vehicle
    
roxo:
  ssl:
    password: ${ROXO_PASSWORD}   
    
opl:
  api:
    url: https://fedexondemanddev.azure-api.net/v2/eta
