logging:
  level:
    root: INFO
    com:
      fedex: DEBUG

spring:
  application:
    name: utility-service
  flyway:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  mvc: 
    throw-exception-if-no-handler-found: true
  web: 
    resources: 
      add-mappings: false
  profiles:
    active: local
    
management:
  endpoints:
    web:
      exposure:
        include: info, health, refresh, configprops
    
info:
  app:
    name: utility-service
    description: FedEx-OnDemand - Utility Service
    
# this needs to be in the common application properties
swagger: 
  service: 
    contact: 
      email: CAVS@fedex.com
      name: "FedEx OnDemand Development Team"
      url: "https://fedex.com/"
    description: "This service is used for handling logic with the FedEx-OnDemand Utility Service."
    license: 
      url: "https://fedex.com/licence"
    name: "FOD utility Service API"
    tos: 
      url: "https://cavs.fexdex.com/termsofuse"
    version: v1
    group: CAVS Open Api Group


itinerary: 
  service: 
    endpoint: https://itinerary-manager-service-dev.cfapps.scus-10.test.cf.fedex.com  

signalr: 
  service:
    key: pTiaZOJPxcoNgdxZT+4tb75hIPt0e5br9S47fRycreo=
    
api:
  version: 3.0.6  
  
envelope:
  version: 0.9
  
azure:  
  eh:
    connectionString: Endpoint=sb://sim-eh-dev.servicebus.windows.net/;SharedAccessKeyName=send-policy;SharedAccessKey=+HNMT5u47yz1JodXtFUhLSNiaZMmX/hH+9qsiv2jF9g=
    name: device-messages
